# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvisUi(object):
    def setupUi(self, jarvisUi):
        jarvisUi.setObjectName("jarvisUi")
        jarvisUi.resize(1365, 755)
        self.centralwidget = QtWidgets.QWidget(jarvisUi)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -20, 1401, 841))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("gif/212508.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 411, 121))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("gif/00545cb7179c504433d4c8f5e845f286.gif"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.texttime = QtWidgets.QTextBrowser(self.centralwidget)
        self.texttime.setGeometry(QtCore.QRect(760, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.texttime.setFont(font)
        self.texttime.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"textcolor:red;")
        self.texttime.setObjectName("texttime")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1060, 500, 101, 41))
        self.pushButton.setStyleSheet("background-color:Transparent;\n"
"font: 24pt \"MS Shell Dlg 2\";\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Microsoft YaHei UI\";\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"textcolor:White;\n"
"color:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(970, 480, 261, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("gif/images (3).jpg"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(970, 550, 261, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("gif/images (3).jpg"))
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1060, 570, 101, 41))
        self.pushButton_2.setStyleSheet("background-color:Transparent;\n"
"font: 24pt \"MS Shell Dlg 2\";\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Microsoft YaHei UI\";\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"textcolor:White;\n"
"color:rgb(255, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textdate = QtWidgets.QTextBrowser(self.centralwidget)
        self.textdate.setGeometry(QtCore.QRect(1060, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textdate.setFont(font)
        self.textdate.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"textcolor:red;")
        self.textdate.setObjectName("textdate")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 380, 451, 381))
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("gif/mk7_Diagnostics_BioFeedback_POV.gif"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(710, 10, 301, 61))
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("gif/text box.webp"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1010, 10, 291, 61))
        self.label_7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("gif/text box.webp"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.label_4.raise_()
        self.pushButton_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.texttime.raise_()
        self.label_7.raise_()
        self.textdate.raise_()
        jarvisUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarvisUi)
        QtCore.QMetaObject.connectSlotsByName(jarvisUi)

    def retranslateUi(self, jarvisUi):
        _translate = QtCore.QCoreApplication.translate
        jarvisUi.setWindowTitle(_translate("jarvisUi", "MainWindow"))
        self.pushButton.setText(_translate("jarvisUi", "Run"))
        self.pushButton_2.setText(_translate("jarvisUi", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisUi = QtWidgets.QMainWindow()
    ui = Ui_jarvisUi()
    ui.setupUi(jarvisUi)
    jarvisUi.show()
    sys.exit(app.exec_())
